/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.dailyDev.view;

import ec.edu.espe.dailyDev.model.Task;
import ec.edu.espe.dailyDev.model.User;
import static ec.edu.espe.dailyDev.utils.FiltersHandler.createFilterTasksById;
import ec.edu.espe.dailyDev.utils.MongoDBHandler;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.bson.conversions.Bson;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Olivier Paspuel
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();  // Generated by NetBeans
        Bson filter = createFilterTasksById(User.getCurrentUserId().toString());  // Modify with your specific filter
        List<Task> tasks = new MongoDBHandler().findAllTasks(filter);
        System.out.println(tasks);
        if (!tasks.isEmpty()) {
            createChart(statusChartIFrm, "status", tasks);
            createChart(priorityChartIFrm, "priority", tasks);

        }
    }

    public static void createChart(JInternalFrame frame, String type, List<Task> tasks) {

        BasicInternalFrameUI bi = (BasicInternalFrameUI) frame.getUI();
        bi.setNorthPane(null);

        DefaultPieDataset dataset = new DefaultPieDataset();

        // Classify tasks based on type (priority or status) and update the dataset
        for (Task task : tasks) {
            String category;
            if ("priority".equals(type)) {
                category = task.getPriority(); // Assuming getPriority() returns "high", "medium", or "low"
            } else if ("status".equals(type)) {
                category = task.isCompleted() ? "Completed" : "Not Completed";
            } else {
                // Handle unsupported type
                throw new IllegalArgumentException("Unsupported type: " + type);
            }

            // Update dataset based on the category
            if (dataset.getKeys().contains(category)) {
                dataset.setValue(category, dataset.getValue(category).intValue() + 1);
            } else {
                dataset.setValue(category, 1);
            }
        }

        JFreeChart pieChart = ChartFactory.createPieChart("Tasks by " + (type.equals("priority") ? "Priority" : "Status"), dataset, true, true, false);
        ChartPanel chartPanel = new ChartPanel(pieChart);
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));
        frame.setContentPane(chartPanel);
        frame.pack();
        frame.setVisible(true);

//        BasicInternalFrameUI bi = (BasicInternalFrameUI) frame.getUI();
//        bi.setNorthPane(null);
//        DefaultPieDataset dataset = new DefaultPieDataset();
//
//        dataset.setValue("Category A", 30);
//        dataset.setValue("Category B", 50);
//        dataset.setValue("Category C", 20);
//
//        JFreeChart barChart = ChartFactory.createPieChart("Bar Chart Example", dataset);
//        ChartPanel chartPanel = new ChartPanel(barChart);
//        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));
//        frame.setContentPane(chartPanel);
//        frame.pack();
//        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        username = new javax.swing.JLabel();
        dashboardActn = new javax.swing.JPanel();
        dashboardLbl = new javax.swing.JLabel();
        taskActn = new javax.swing.JPanel();
        taskLbl = new javax.swing.JLabel();
        scheduleActn = new javax.swing.JPanel();
        scheduleLbl = new javax.swing.JLabel();
        dailyActn = new javax.swing.JPanel();
        dailyLbl = new javax.swing.JLabel();
        adminActn = new javax.swing.JPanel();
        adminLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TBPMain = new javax.swing.JTabbedPane();
        dashboardTab = new javax.swing.JPanel();
        dashboardTitlePnl = new javax.swing.JPanel();
        dashboardTitleLbl = new javax.swing.JLabel();
        currentTasksPnl = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        chartsPnl = new javax.swing.JPanel();
        statusChartIFrm = new javax.swing.JInternalFrame();
        priorityChartIFrm = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        TESTING = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1080, 720));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 0, 0));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, -1));

        username.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");
        username.setIconTextGap(11);
        sidebar.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 70));

        dashboardActn.setBackground(new java.awt.Color(0, 0, 0));
        dashboardActn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardActn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardActn.setOpaque(false);
        dashboardActn.setPreferredSize(new java.awt.Dimension(220, 60));
        dashboardActn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardActnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardActnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardActnMouseExited(evt);
            }
        });

        dashboardLbl.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        dashboardLbl.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardLbl.setText("Dashboard");
        dashboardLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        dashboardLbl.setIconTextGap(10);
        dashboardLbl.setPreferredSize(new java.awt.Dimension(220, 60));

        javax.swing.GroupLayout dashboardActnLayout = new javax.swing.GroupLayout(dashboardActn);
        dashboardActn.setLayout(dashboardActnLayout);
        dashboardActnLayout.setHorizontalGroup(
            dashboardActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardActnLayout.createSequentialGroup()
                .addComponent(dashboardLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dashboardActnLayout.setVerticalGroup(
            dashboardActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidebar.add(dashboardActn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 60));

        taskActn.setBackground(new java.awt.Color(0, 0, 0));
        taskActn.setForeground(new java.awt.Color(255, 255, 255));
        taskActn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taskActn.setOpaque(false);
        taskActn.setPreferredSize(new java.awt.Dimension(220, 60));
        taskActn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                taskActnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                taskActnMouseExited(evt);
            }
        });

        taskLbl.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        taskLbl.setForeground(new java.awt.Color(255, 255, 255));
        taskLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taskLbl.setText("Tasks");
        taskLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        taskLbl.setIconTextGap(10);
        taskLbl.setPreferredSize(new java.awt.Dimension(220, 60));

        javax.swing.GroupLayout taskActnLayout = new javax.swing.GroupLayout(taskActn);
        taskActn.setLayout(taskActnLayout);
        taskActnLayout.setHorizontalGroup(
            taskActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskActnLayout.createSequentialGroup()
                .addComponent(taskLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        taskActnLayout.setVerticalGroup(
            taskActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidebar.add(taskActn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 60));

        scheduleActn.setBackground(new java.awt.Color(0, 0, 0));
        scheduleActn.setForeground(new java.awt.Color(255, 255, 255));
        scheduleActn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scheduleActn.setOpaque(false);
        scheduleActn.setPreferredSize(new java.awt.Dimension(220, 60));
        scheduleActn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scheduleActnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scheduleActnMouseExited(evt);
            }
        });

        scheduleLbl.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        scheduleLbl.setForeground(new java.awt.Color(255, 255, 255));
        scheduleLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        scheduleLbl.setText("Schedule");
        scheduleLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        scheduleLbl.setIconTextGap(10);
        scheduleLbl.setPreferredSize(new java.awt.Dimension(220, 60));

        javax.swing.GroupLayout scheduleActnLayout = new javax.swing.GroupLayout(scheduleActn);
        scheduleActn.setLayout(scheduleActnLayout);
        scheduleActnLayout.setHorizontalGroup(
            scheduleActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scheduleActnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scheduleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        scheduleActnLayout.setVerticalGroup(
            scheduleActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleActnLayout.createSequentialGroup()
                .addComponent(scheduleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(scheduleActn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        dailyActn.setBackground(new java.awt.Color(0, 0, 0));
        dailyActn.setForeground(new java.awt.Color(255, 255, 255));
        dailyActn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dailyActn.setOpaque(false);
        dailyActn.setPreferredSize(new java.awt.Dimension(220, 60));
        dailyActn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dailyActnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dailyActnMouseExited(evt);
            }
        });

        dailyLbl.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        dailyLbl.setForeground(new java.awt.Color(255, 255, 255));
        dailyLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dailyLbl.setText("Daily Message");
        dailyLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        dailyLbl.setIconTextGap(10);
        dailyLbl.setPreferredSize(new java.awt.Dimension(220, 60));

        javax.swing.GroupLayout dailyActnLayout = new javax.swing.GroupLayout(dailyActn);
        dailyActn.setLayout(dailyActnLayout);
        dailyActnLayout.setHorizontalGroup(
            dailyActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dailyActnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dailyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dailyActnLayout.setVerticalGroup(
            dailyActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dailyActnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dailyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidebar.add(dailyActn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 220, 60));

        adminActn.setBackground(new java.awt.Color(0, 0, 0));
        adminActn.setForeground(new java.awt.Color(255, 255, 255));
        adminActn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminActn.setOpaque(false);
        adminActn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminActnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminActnMouseExited(evt);
            }
        });

        adminLbl.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        adminLbl.setForeground(new java.awt.Color(255, 255, 255));
        adminLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adminLbl.setText("User Administration");
        adminLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        adminLbl.setIconTextGap(10);
        adminLbl.setPreferredSize(new java.awt.Dimension(220, 60));

        javax.swing.GroupLayout adminActnLayout = new javax.swing.GroupLayout(adminActn);
        adminActn.setLayout(adminActnLayout);
        adminActnLayout.setHorizontalGroup(
            adminActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminActnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(adminLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        adminActnLayout.setVerticalGroup(
            adminActnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidebar.add(adminActn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 220, 60));

        background.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 720));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 860, 70));

        TBPMain.setBackground(new java.awt.Color(255, 255, 255));

        dashboardTab.setBackground(new java.awt.Color(217, 217, 217));

        dashboardTitlePnl.setBackground(new java.awt.Color(255, 255, 255));

        dashboardTitleLbl.setBackground(new java.awt.Color(255, 255, 255));
        dashboardTitleLbl.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        dashboardTitleLbl.setText("Dashboard");
        dashboardTitleLbl.setToolTipText("");
        dashboardTitleLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));

        javax.swing.GroupLayout dashboardTitlePnlLayout = new javax.swing.GroupLayout(dashboardTitlePnl);
        dashboardTitlePnl.setLayout(dashboardTitlePnlLayout);
        dashboardTitlePnlLayout.setHorizontalGroup(
            dashboardTitlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitleLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dashboardTitlePnlLayout.setVerticalGroup(
            dashboardTitlePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitleLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        currentTasksPnl.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Today's Pending Tasks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Light", 0, 12))); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(170, 30));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Pending Tasks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Light", 0, 12))); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(170, 130));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Today's completed tasks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Light", 0, 12))); // NOI18N
        jPanel12.setPreferredSize(new java.awt.Dimension(170, 30));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Next pending task", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Light", 0, 12))); // NOI18N
        jPanel13.setPreferredSize(new java.awt.Dimension(170, 30));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout currentTasksPnlLayout = new javax.swing.GroupLayout(currentTasksPnl);
        currentTasksPnl.setLayout(currentTasksPnlLayout);
        currentTasksPnlLayout.setHorizontalGroup(
            currentTasksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTasksPnlLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        currentTasksPnlLayout.setVerticalGroup(
            currentTasksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentTasksPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentTasksPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        statusChartIFrm.setBorder(null);
        statusChartIFrm.setPreferredSize(new java.awt.Dimension(300, 300));
        statusChartIFrm.setVisible(true);

        javax.swing.GroupLayout statusChartIFrmLayout = new javax.swing.GroupLayout(statusChartIFrm.getContentPane());
        statusChartIFrm.getContentPane().setLayout(statusChartIFrmLayout);
        statusChartIFrmLayout.setHorizontalGroup(
            statusChartIFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        statusChartIFrmLayout.setVerticalGroup(
            statusChartIFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        priorityChartIFrm.setBorder(null);
        priorityChartIFrm.setPreferredSize(new java.awt.Dimension(300, 300));
        priorityChartIFrm.setVisible(true);

        javax.swing.GroupLayout priorityChartIFrmLayout = new javax.swing.GroupLayout(priorityChartIFrm.getContentPane());
        priorityChartIFrm.getContentPane().setLayout(priorityChartIFrmLayout);
        priorityChartIFrmLayout.setHorizontalGroup(
            priorityChartIFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        priorityChartIFrmLayout.setVerticalGroup(
            priorityChartIFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout chartsPnlLayout = new javax.swing.GroupLayout(chartsPnl);
        chartsPnl.setLayout(chartsPnlLayout);
        chartsPnlLayout.setHorizontalGroup(
            chartsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartsPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(priorityChartIFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusChartIFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chartsPnlLayout.setVerticalGroup(
            chartsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartsPnlLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(chartsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priorityChartIFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusChartIFrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashboardTabLayout = new javax.swing.GroupLayout(dashboardTab);
        dashboardTab.setLayout(dashboardTabLayout);
        dashboardTabLayout.setHorizontalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chartsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentTasksPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardTitlePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashboardTabLayout.setVerticalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardTitlePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentTasksPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TBPMain.addTab("tab1", dashboardTab);

        javax.swing.GroupLayout TESTINGLayout = new javax.swing.GroupLayout(TESTING);
        TESTING.setLayout(TESTINGLayout);
        TESTINGLayout.setHorizontalGroup(
            TESTINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        TESTINGLayout.setVerticalGroup(
            TESTINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(TESTING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 106, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TESTING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        TBPMain.addTab("tab3", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        TBPMain.addTab("tab4", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        TBPMain.addTab("tab5", jPanel6);

        background.add(TBPMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 860, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleMouseEnter(Component component, JLabel label, String iconPath) {
        component.setBackground(Color.WHITE);
        label.setForeground(Color.BLACK);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconPath)));
    }

    private void handleMouseExit(Component component, JLabel label, String iconPath) {
        component.setBackground(Color.BLACK);
        label.setForeground(Color.WHITE);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconPath)));
    }


    private void adminActnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminActnMouseEntered
        handleMouseEnter(adminActn, adminLbl, "/imgs/adminIconBlack.png");
    }//GEN-LAST:event_adminActnMouseEntered

    private void dailyActnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyActnMouseEntered
        handleMouseEnter(dailyActn, dailyLbl, "/imgs/dailyIconBlack.png");
    }//GEN-LAST:event_dailyActnMouseEntered

    private void scheduleActnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleActnMouseEntered
        handleMouseEnter(scheduleActn, scheduleLbl, "/imgs/scheduleIconBlack.png");
    }//GEN-LAST:event_scheduleActnMouseEntered

    private void taskActnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskActnMouseEntered
        handleMouseEnter(taskActn, taskLbl, "/imgs/taskIconBlack.png");
    }//GEN-LAST:event_taskActnMouseEntered

    private void dashboardActnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardActnMouseExited
        handleMouseExit(dashboardActn, dashboardLbl, "/imgs/dashboardIcon.png");
    }//GEN-LAST:event_dashboardActnMouseExited

    private void taskActnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskActnMouseExited
        handleMouseExit(taskActn, taskLbl, "/imgs/taskIcon.png");
    }//GEN-LAST:event_taskActnMouseExited

    private void scheduleActnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleActnMouseExited
        handleMouseExit(scheduleActn, scheduleLbl, "/imgs/scheduleIcon.png");
    }//GEN-LAST:event_scheduleActnMouseExited

    private void dailyActnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyActnMouseExited
        handleMouseExit(dailyActn, dailyLbl, "/imgs/dailyIcon.png");
    }//GEN-LAST:event_dailyActnMouseExited

    private void adminActnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminActnMouseExited
        handleMouseExit(adminActn, adminLbl, "/imgs/adminIcon.png");
    }//GEN-LAST:event_adminActnMouseExited

    private void dashboardActnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardActnMouseEntered
        handleMouseEnter(dashboardActn, dashboardLbl, "/imgs/dashboardIconBlack.png");
    }//GEN-LAST:event_dashboardActnMouseEntered

    private void dashboardActnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardActnMouseClicked
        JOptionPane.showMessageDialog(rootPane, User.getCurrentUserId());

    }//GEN-LAST:event_dashboardActnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TBPMain;
    private javax.swing.JPanel TESTING;
    private javax.swing.JPanel adminActn;
    private javax.swing.JLabel adminLbl;
    private javax.swing.JPanel background;
    private javax.swing.JPanel chartsPnl;
    private javax.swing.JPanel currentTasksPnl;
    private javax.swing.JPanel dailyActn;
    private javax.swing.JLabel dailyLbl;
    private javax.swing.JPanel dashboardActn;
    private javax.swing.JLabel dashboardLbl;
    private javax.swing.JPanel dashboardTab;
    private javax.swing.JLabel dashboardTitleLbl;
    private javax.swing.JPanel dashboardTitlePnl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JInternalFrame priorityChartIFrm;
    private javax.swing.JPanel scheduleActn;
    private javax.swing.JLabel scheduleLbl;
    private javax.swing.JPanel sidebar;
    private javax.swing.JInternalFrame statusChartIFrm;
    private javax.swing.JPanel taskActn;
    private javax.swing.JLabel taskLbl;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
