/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.dailyDev.view;

/**
 *
 * @author dvill
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutPnl = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        imageLbl = new javax.swing.JLabel();
        logoLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        signinlbl = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        userSprt = new javax.swing.JSeparator();
        passwordSprt = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        layoutPnl.setBackground(new java.awt.Color(255, 255, 255));
        layoutPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLbl.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(217, 217, 217));
        nameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLbl.setText("DAILYDEV");
        layoutPnl.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, -1));

        imageLbl.setBackground(new java.awt.Color(255, 255, 255));
        imageLbl.setText("Image");
        layoutPnl.add(imageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 480));

        logoLbl.setText("LOGO");
        layoutPnl.add(logoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 120, 30));

        passwordLbl.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        passwordLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passwordLbl.setText("PASSWORD");
        layoutPnl.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 90, 30));

        signinlbl.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        signinlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signinlbl.setText("SIGN IN");
        layoutPnl.add(signinlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 170, 30));

        userLbl.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        userLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userLbl.setText("USER");
        layoutPnl.add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 50, 30));

        userTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        userTxt.setForeground(new java.awt.Color(204, 204, 204));
        userTxt.setText("Enter your user ");
        userTxt.setBorder(null);
        layoutPnl.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 320, -1));
        layoutPnl.add(userSprt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 310, -1));
        layoutPnl.add(passwordSprt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 310, -1));

        jPasswordField1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        layoutPnl.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 310, -1));

        loginPnl.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout loginPnlLayout = new javax.swing.GroupLayout(loginPnl);
        loginPnl.setLayout(loginPnlLayout);
        loginPnlLayout.setHorizontalGroup(
            loginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        loginPnlLayout.setVerticalGroup(
            loginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        layoutPnl.add(loginPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layoutPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layoutPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel layoutPnl;
    private javax.swing.JPanel loginPnl;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JSeparator passwordSprt;
    private javax.swing.JLabel signinlbl;
    private javax.swing.JLabel userLbl;
    private javax.swing.JSeparator userSprt;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
